// components/Home/Hero.vue
<template>
    <div class="bg-gradient-to-tr from-gray-900 to-gray-800 py-24">
        <div class="custom-container flex items-center justify-between px-4">
            <div>
                <h1 class="text-6xl font-bold uppercase text-white">
                    {{ hero.title }}
                </h1>
                <p class="mt-4 max-w-lg text-lg text-gray-400">
                    {{ hero.description }}
                </p>
                <div class="mt-8 flex items-center space-x-4">
                    <NuxtLink to="/#content"
                        ><Button>{{ hero.cta.knowMore }}</Button></NuxtLink
                    >
                    <NuxtLink to="/contact"
                        ><Button type="gray">{{
                            hero.cta.contact
                        }}</Button></NuxtLink
                    >
                </div>
            </div>
            <div>IMAGE</div>
        </div>
    </div>
</template>

<script setup lang="ts">
import { hero } from "~/assets/content/home.json";
</script>

// components/sections/Home/Hero.tsx
import Link from 'next/link'
import Button from '~/components/Button'
import homeContent from '~/content/home.json'

export default function Hero() {
    const { hero } = homeContent

    return (
        <div className="custom-container py-10 lg:py-24">
            <div className="lg:grid lg:grid-cols-12 lg:gap-8">
                <div className="sm:text-center md:mx-auto md:max-w-2xl lg:col-span-6 lg:text-left">
                    <h1>
                        <span className="mt-1 block text-4xl font-bold tracking-tight sm:text-5xl xl:text-6xl">
                            <span className="block text-gray-900">
                                {hero.title1}
                            </span>
                            <span className="bg-gradient text-gradient block">
                                {hero.title2}
                            </span>
                        </span>
                    </h1>
                    <p className="mt-3 text-base text-gray-700 sm:mt-5 sm:text-xl lg:text-lg xl:text-xl">
                        {hero.description}
                    </p>
                    <div className="mt-8 grid gap-4 sm:grid-cols-2 md:flex">
                        <Button
                            as={Link}
                            href="/contact"
                            className="w-full justify-center lg:w-auto lg:justify-start"
                        >
                            {hero.cta.contact}
                        </Button>
                        <Button
                            as={Link}
                            href="/#solutions"
                            scroll={false}
                            color="gray"
                            className="w-full justify-center lg:w-auto lg:justify-start"
                        >
                            {hero.cta.knowMore}
                        </Button>
                    </div>
                </div>
                <div className="relative mt-12 sm:mx-auto sm:max-w-lg lg:col-span-6 lg:mx-0 lg:mt-0 lg:flex lg:max-w-none lg:items-center">
                    <div className="relative mx-auto w-full overflow-hidden rounded-lg shadow-lg lg:max-w-md">
                        <img
                            className="w-full"
                            src={hero.image.url}
                            alt={hero.image.alt}
                        />
                    </div>
                </div>
            </div>
        </div>
    )
}
