// components/Button.tsx
import clsx from 'clsx'
import React, { forwardRef } from 'react'

type Props = {
    component?: React.Component | string
    children: React.ReactNode
    type?: 'primary' | 'gray' | 'white'
    size?: 'small' | 'medium'
} & React.HTMLAttributes<any>

const Button = forwardRef<any, Props>(
    (
        {
            component = 'button',
            children,
            type = 'primary',
            size = 'medium',
            className,
            ...rest
        },
        ref
    ) => {
        const typeClass = {
            primary:
                'bg-gradient text-white hover:from-primary-500 hover:to-primary-400 focus:ring-primary-200',
            gray: 'bg-gray-700 text-gray-100 hover:bg-gray-600 focus:ring-gray-500',
            white: 'bg-white text-gray-700 hover:bg-gray-50 focus:ring-primary-500',
        }[type]
        const sizeClass = {
            small: 'py-1 px-4',
            medium: 'px-6 py-3',
        }[size]

        const Element = component as React.ElementType

        return (
            <Element
                ref={ref}
                className={clsx(
                    'rounded-lg font-medium uppercase transition-all focus:outline-none focus:ring-2',
                    typeClass,
                    sizeClass,
                    className
                )}
                {...rest}
            >
                {children}
            </Element>
        )
    }
)

export default Button

// components/Button.vue
<template>
    <button :class="classes"><slot /></button>
</template>

<script setup lang="ts">
import { PropType } from "vue";

type ButtonType = "primary" | "gray" | "white";
type ButtonSize = "small" | "medium";

const { type, size } = defineProps({
    type: {
        type: String as PropType<ButtonType>,
        default: "primary",
    },
    size: {
        type: String as PropType<ButtonSize>,
        default: "medium",
    },
});

const typeClass = {
    primary:
        "bg-gradient text-white hover:from-primary-500 hover:to-primary-400",
    gray: "bg-gray-700 text-gray-100 hover:bg-gray-600",
    white: "bg-white text-gray-700 hover:bg-gray-50",
}[type];
const sizeClass = {
    small: "py-1 px-4",
    medium: "px-6 py-3",
}[size];

const classes: string[] = [
    "font-medium rounded-lg transition-all uppercase",
    typeClass,
    sizeClass,
];
</script>
