// components/Header.vue
<template>
    <header class="sticky top-0 border-b border-gray-200 bg-white">
        <Popover class="relative" v-slot="{ close }">
            <div
                class="custom-container flex items-center justify-between px-4 py-3"
            >
                <div class="flex items-center space-x-6">
                    <div class="flex items-center space-x-2">
                        <img class="h-10" src="/logo.png" />
                        <span class="text-2xl font-bold text-primary-500"
                            >SIDEELEC</span
                        >
                    </div>
                    <div class="hidden items-center space-x-4 md:flex">
                        <NuxtLink
                            v-for="{ href, name } in links"
                            :to="href"
                            class="font-medium text-gray-500 transition-colors hover:text-gray-600"
                            >{{ name }}</NuxtLink
                        >
                    </div>
                </div>
                <div class="flex items-center space-x-2">
                    <NuxtLink to="/contact">
                        <Button size="small">CONTACT</Button>
                    </NuxtLink>
                    <PopoverButton
                        class="inline-flex items-center justify-center rounded-lg bg-gray-200 p-1.5 text-gray-800 transition-all hover:bg-gray-300 focus:outline-none focus:ring-2 focus:ring-primary-500 md:hidden"
                    >
                        <span class="sr-only">Open menu</span>
                        <MenuIcon class="h-5 w-5" aria-hidden="true" />
                    </PopoverButton>
                </div>
            </div>
            <transition
                enter-active-class="duration-200 ease-out"
                enter-from-class="scale-95 opacity-0"
                enter-to-class="scale-100 opacity-100"
                leave-active-class="duration-100 ease-in"
                leave-from-class="scale-100 opacity-100"
                leave-to-class="scale-95 opacity-0"
            >
                <PopoverPanel
                    focus
                    class="fixed inset-0 z-50 flex origin-center transform items-center justify-center bg-white p-4 transition md:hidden"
                >
                    <PopoverButton
                        class="absolute top-4 right-4 inline-flex items-center justify-center rounded-md bg-gray-200 p-1.5 text-gray-800 transition-all hover:bg-gray-300 focus:ring-2 focus:ring-primary-500"
                    >
                        <span class="sr-only">Close menu</span>
                        <XIcon class="h-5 w-5" aria-hidden="true" />
                    </PopoverButton>
                    <div
                        class="flex flex-col items-center justify-center space-y-6 text-xl"
                    >
                        <NuxtLink
                            v-for="{ href, name } in links"
                            :to="href"
                            @click.native="() => close()"
                            class="animated-underline relative inline-flex items-center space-x-1 font-medium text-gray-500"
                            :class="{
                                'bg-gradient text-gradient font-bold':
                                    href === '/'
                                        ? $route.path === '/'
                                        : $route.path.startsWith(href),
                            }"
                        >
                            <span>{{ name }}</span>
                        </NuxtLink>
                    </div>
                </PopoverPanel>
            </transition>
        </Popover>
    </header>
</template>

<script setup lang="ts">
import { PopoverButton, PopoverPanel, Popover } from "@headlessui/vue";
import { MenuIcon, XIcon } from "@heroicons/vue/outline";

const links: { name: string; href: string }[] = [
    {
        name: "Accueil",
        href: "/",
    },
    {
        name: "Solutions",
        href: "/solutions",
    },
    {
        name: "Services",
        href: "/services",
    },
    {
        name: "L'entreprise",
        href: "/l-entreprise",
    },
    {
        name: "Nouveautés",
        href: "/nouveautes",
    },
];
</script>

// next/components/Header.tsx
import { Popover, Transition } from "@headlessui/react";
import { MenuIcon, XIcon } from "@heroicons/react/outline";
import clsx from "clsx";
import Link from "next/link";
import { useRouter } from "next/router";
import React from "react";
import { useEffect } from "react";
import Button from "./Button";

const links: { name: string; href: string }[] = [
    {
        name: "Accueil",
        href: "/",
    },
    {
        name: "Solutions",
        href: "/solutions",
    },
    {
        name: "Services",
        href: "/services",
    },
    {
        name: "L'entreprise",
        href: "/l-entreprise",
    },
    {
        name: "Nouveautés",
        href: "/nouveautes",
    },
];

const Header = () => {
    const { pathname } = useRouter();

    return (
        <header className="sticky top-0 border-b border-gray-200 bg-white">
            <Popover className="relative">
                <div className="custom-container flex items-center justify-between px-4 py-3">
                    <div className="flex items-center space-x-6">
                        <div className="flex items-center space-x-2">
                            <img className="h-10" src="/logo.png" />
                            <span className="text-2xl font-bold text-primary-500">
                                SIDEELEC
                            </span>
                        </div>
                        <div className="hidden items-center space-x-4 md:flex">
                            {links.map(({ href, name }) => (
                                <Link href={href} key={href}>
                                    <a className="font-medium text-gray-500 transition-colors hover:text-gray-600">
                                        {name}
                                    </a>
                                </Link>
                            ))}
                        </div>
                    </div>
                    <div className="flex items-center space-x-2">
                        <Link href="/contact" passHref>
                            <Button component="a" size="small">
                                CONTACT
                            </Button>
                        </Link>
                        <Popover.Button className="inline-flex items-center justify-center rounded-lg bg-gray-200 p-1.5 text-gray-800 transition-all hover:bg-gray-300 focus:outline-none focus:ring-2 focus:ring-primary-500 md:hidden">
                            <span className="sr-only">Open menu</span>
                            <MenuIcon className="h-5 w-5" aria-hidden="true" />
                        </Popover.Button>
                    </div>
                </div>
                <Transition
                    enter="duration-200 ease-out"
                    enterFrom="scale-95 opacity-0"
                    enterTo="scale-100 opacity-100"
                    leave="duration-100 ease-in"
                    leaveFrom="scale-100 opacity-100"
                    leaveTo="scale-95 opacity-0"
                    as={React.Fragment}
                >
                    <Popover.Panel
                        focus
                        className="fixed inset-0 z-50 flex origin-center transform items-center justify-center bg-white p-4 transition md:hidden"
                    >
                        {({ close }) => (
                            <>
                                <Popover.Button className="absolute top-4 right-4 inline-flex items-center justify-center rounded-md bg-gray-200 p-1.5 text-gray-800 transition-all hover:bg-gray-300 focus:ring-2 focus:ring-primary-500">
                                    <span className="sr-only">Close menu</span>
                                    <XIcon
                                        className="h-5 w-5"
                                        aria-hidden="true"
                                    />
                                </Popover.Button>
                                <div className="flex flex-col items-center justify-center space-y-6 text-xl">
                                    {links.map(({ href, name }) => (
                                        <Link key={href} href={href}>
                                            <a
                                                onClick={() => close()}
                                                className={clsx(
                                                    "animated-underline relative inline-flex items-center space-x-1 font-medium text-gray-500",
                                                    (href === "/"
                                                        ? pathname === "/"
                                                        : pathname.startsWith(
                                                              href
                                                          )) &&
                                                        "bg-gradient text-gradient font-bold"
                                                )}
                                            >
                                                {name}
                                            </a>
                                        </Link>
                                    ))}
                                </div>
                            </>
                        )}
                    </Popover.Panel>
                </Transition>
            </Popover>
        </header>
    );
};

export default Header;
